import { IsString, IsNotEmpty, IsNumber, IsOptional, IsEnum, IsUUID, IsArray, IsDateString, Min } from 'class-validator';
import { PurchaseOrderStatus, PurchaseOrderItem } from '../entities/purchase-order.entity';

export class CreatePurchaseOrderDto {
  @IsUUID()
  @IsNotEmpty()
  supplierId: string;

  @IsArray()
  @IsNotEmpty()
  items: PurchaseOrderItem[];

  @IsNumber()
  @IsNotEmpty()
  subtotal: number;

  @IsNumber()
  @IsNotEmpty()
  taxTotal: number;

  @IsNumber()
  @IsNotEmpty()
  total: number;

  @IsDateString()
  @IsNotEmpty()
  expectedDate: Date;

  @IsDateString()
  @IsOptional()
  receivedDate?: Date;

  @IsOptional()
  isAutoGenerated?: boolean;

  @IsString()
  @IsOptional()
  notes?: string;
}

export class UpdatePurchaseOrderStatusDto {
  @IsEnum(PurchaseOrderStatus)
  status: PurchaseOrderStatus;
}

export class ReceivePurchaseOrderDto {
  @IsArray()
  @IsNotEmpty()
  items: { productId: string; quantity: number }[];

  @IsUUID()
  @IsOptional()
  warehouseId?: string;
}
